// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKuIb_3_hMerVGRMxoZFYCqEu45Y4eGgQ',
    appId: '1:154895823531:web:1c8da7036a792d2fedbdee',
    messagingSenderId: '154895823531',
    projectId: 'uploadimage-e694d',
    authDomain: 'uploadimage-e694d.firebaseapp.com',
    storageBucket: 'uploadimage-e694d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx0hI0IQxj_Paig6F4lPPdaA0t7p3QyuY',
    appId: '1:154895823531:android:545b47f748b2a2a2edbdee',
    messagingSenderId: '154895823531',
    projectId: 'uploadimage-e694d',
    storageBucket: 'uploadimage-e694d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1ZPhNPgWAtJCqXslAOANyUrTfp5JNqs',
    appId: '1:154895823531:ios:c49007048680e0c3edbdee',
    messagingSenderId: '154895823531',
    projectId: 'uploadimage-e694d',
    storageBucket: 'uploadimage-e694d.appspot.com',
    iosBundleId: 'com.example.flexx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX1ZPhNPgWAtJCqXslAOANyUrTfp5JNqs',
    appId: '1:154895823531:ios:c49007048680e0c3edbdee',
    messagingSenderId: '154895823531',
    projectId: 'uploadimage-e694d',
    storageBucket: 'uploadimage-e694d.appspot.com',
    iosBundleId: 'com.example.flexx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96Pehu0_phZAD4yNcT7YL_RXcrtY3Ziw',
    appId: '1:154895823531:web:78a1aa65623536ddedbdee',
    messagingSenderId: '154895823531',
    projectId: 'uploadimage-e694d',
    authDomain: 'uploadimage-e694d.firebaseapp.com',
    storageBucket: 'uploadimage-e694d.appspot.com',
  );

}