// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJw-xmniKREKNZtcRn9ID5yJnONqFTd4',
    appId: '1:1073242722303:web:265b12aac47f76653f21ca',
    messagingSenderId: '1073242722303',
    projectId: 'flexx-6d274',
    authDomain: 'flexx-6d274.firebaseapp.com',
    storageBucket: 'flexx-6d274.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEiZDljPQe6LtnqFH_oRG1H6VxB01SXPg',
    appId: '1:1073242722303:android:5b583690b952275e3f21ca',
    messagingSenderId: '1073242722303',
    projectId: 'flexx-6d274',
    storageBucket: 'flexx-6d274.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVv8BnPJBhymPqSabAWaaAZz1UdG417i0',
    appId: '1:1073242722303:ios:9c2cee7b9fc228073f21ca',
    messagingSenderId: '1073242722303',
    projectId: 'flexx-6d274',
    storageBucket: 'flexx-6d274.firebasestorage.app',
    iosBundleId: 'com.example.flexx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVv8BnPJBhymPqSabAWaaAZz1UdG417i0',
    appId: '1:1073242722303:ios:9c2cee7b9fc228073f21ca',
    messagingSenderId: '1073242722303',
    projectId: 'flexx-6d274',
    storageBucket: 'flexx-6d274.firebasestorage.app',
    iosBundleId: 'com.example.flexx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACJw-xmniKREKNZtcRn9ID5yJnONqFTd4',
    appId: '1:1073242722303:web:4c9a376695f3dd073f21ca',
    messagingSenderId: '1073242722303',
    projectId: 'flexx-6d274',
    authDomain: 'flexx-6d274.firebaseapp.com',
    storageBucket: 'flexx-6d274.firebasestorage.app',
  );
}
